config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'movies/search'
  root 'movies#search'
  resources :movies,only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index' => 'hello#index'
  resources :posts  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags, dependent: :destroy


    belongs_to :user
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tags, dependent: :destroy
    has_many :posts, through: :post_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

          has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!

  def search
    if params[:looking_for]
      movie_title = params[:looking_for]
      url = URI.encode('https://api.themoviedb.org/3/search/movie?api_key=150363785ff664359067f5e9ccbe5883&language=ja&query=' + movie_title)
    else
      url = 'https://api.themoviedb.org/3/movie/popular?api_key=150363785ff664359067f5e9ccbe5883&language=ja'
    end
    @movies = JSON.parse(Net::HTTP.get(URI.parse(url))) 
  end

  def show
    movie_id = params[:id]
    url = URI.encode('https://api.themoviedb.org/3/movie/'+ movie_id +'?api_key=150363785ff664359067f5e9ccbe5883&language=ja')
    @movie = JSON.parse(Net::HTTP.get(URI.parse(url)))
  end
end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!

  def index
    @tags = Tag.all
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all.order(id: "DESC")
  end

  def new
    @post = Post.new
    movie_id = params[:movie_id]
    url = URI.encode('https://api.themoviedb.org/3/movie/'+ movie_id +'?api_key=150363785ff664359067f5e9ccbe5883&language=ja')
    @movie = JSON.parse(Net::HTTP.get(URI.parse(url)))
  end

  def create
    post = Post.new(post_params)

    post.user_id = current_user.id

    if post.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end


  def show
    @post = Post.find(params[:id])
    
  end 

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to :action => "show", :id => post.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to action: :index
  end


  private
  def post_params
    params.require(:post).permit(:title, :year, :genre, :description, :image, :hoken, tag_ids: [] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/hello/index.html.erb
<%= link_to "ログイン", movies_search_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareShareMovie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/search.html.erb
<div class="ishimon">
    <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <div class="toptitle2">
        <h1>★Search Movie Title & Post★</h1>
        <h2><%= link_to "Meet Awesome Movie", posts_path%></h2><br>
        <div class="ayanochan">
        <br>
        <p>こちらは『映画名検索＆投稿』ページです。</p>
        <p>直感で検索したい方は<%= link_to "こちらへ", posts_path %> </p>
        <br>
        </div>
        <br>
        <br>
        <h6>※空欄で検索ボタンを押すとエラーが出ます。</h6>
            <div>
                <%= form_tag(root_path, method: :get) do %>
                    <%= search_field_tag :looking_for, nil, placeholder: 'Movie Title...' , :size => "40*40" %>
                    <%= submit_tag 'search' %>
                <% end %>
            </div>
    </div>
    <br>
    <div class = "container">
        <% @movies['results'].each do |movie| %>
            <div class = "data">
                <%= movie['title'] %>
                <p><%= link_to "詳細・投稿", movie_path(movie['id']) %></p>
                <p><%#= movie['release_date'] %></p>
                <p><%#= movie['id'] %></p>
                <% @movie_id = movie['id'] %>
                <% if movie['poster_path']  %>
                    <p><%= image_tag 'https://image.tmdb.org/t/p/w200' + movie['poster_path'],class: "card-img" %></p>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/movies/show.html.erb
<div class="ishimon">

<br>
    <div class="btn3">
        <%= link_to "映画検索", movies_search_path , class: 'okawa' %>
        <%= link_to "投稿一覧へ", posts_path , class: 'okawa' %>
    </div>
    <div class="movie">
        <h1><p><%= @movie['title'] %></p></h1>
        <p><%= @movie['release_date'] %></p>
        <% movie_id = @movie['id'] %>
        <br>
        <h2><%= link_to "投稿ページへ", new_post_path(movie_id: @movie['id']) ,class:'postbtn' %></h2>
        <br>
        <p><%#= @movie['id'] %></p>
            <p><% if @movie['poster_path'] %>
                    <%= image_tag 'https://image.tmdb.org/t/p/w200' + @movie['poster_path'],class: "card-size" %>
                <% end %>
            </p>
        <br>
            <div class = kaigyo>
                <p><%= @movie['overview'] %></p>
            </div>
            <br>
        <h2><%= link_to "投稿ページへ", new_post_path(movie_id: @movie['id']) ,class:'postbtn' %></h2>
    </div>
    <br>
</div>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>
<%= form_for @post do |f| %>
  <%= f.label :body %>
<p> <%= f.text_field :title, :size => 140 %> </p>
<p> <%= f.text_field :year, :size => 140 %> </p>
<p> <%= f.text_field :description, :size => 140 %></p>
<%= f.submit "編集する" %>
<% end %>

app/views/posts/index.html.erb
<div class="ishimon"> 
    <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <div class="toptitle">
      <h1>★Meet Awesome Movie★</h1>
      <h2><%= link_to "Search Movie Title & Post", movies_search_path %></h2><br>

        <div class="ayanochan">
        <br>
          <p>こちらは『普通の映画検索に飽きた』『みんなのオススメを知りたい』</p>
          <p>といった悩みを解決する『直感で映画に出会える』ページ。</p>
          <p>あなたの映画体験を共有するなら<%= link_to "こちらへ", movies_search_path %></p><br>
        </div>

        <br>
        <br>

          <p>ジャンル検索はこちら!</p>
          <p>↓  ↓  ↓</p>
          <br>
          <%= form_tag posts_path, method: :get, class: 'boards__searchForm' do %>

            <%= select_tag :tag_id,
                            options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                          {prompt: '全ての映画を表示',onchange: 'submit(this.form);'}%>
          <% end %>
          <br>
        
    </div>
    <div class="posts-container">
      <% @posts.each do |t| %>
        <div class="post">
          <p><%#= t.title %></p>
          <p><%#= link_to "詳細・コメント", post_path(t.id) %></p>
          <p class="nakayan"><%= link_to t.title, post_path(t.id)%></p>
          <div class="subtitle">
            <p><%= t.genre %></p>
          </div>
          <p><%#= t.description %></p>
          <% if t.image %>
            <%= image_tag t.image ,class: "card"%>
          <% end %>

          <% if user_signed_in? && current_user.id == t.user_id %>
          <%= button_to "削除する", post_path(t.id), method: :delete %>
          <% end %>
        </div>

      <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<div class="tomocchi">
<br>
    <div class="btn3">
        <%= link_to "映画検索", movies_search_path ,class:'okawa' %>
        <%= link_to "投稿一覧へ", posts_path , class:'okawa' %>
    </div>
    <%= form_for @post do |f| %>
        <div class="movie">
                <p> <%= f.hidden_field :title, :size => 140, value: @movie['title']%> </p>
                <p> <%= f.hidden_field :year, :size => 140, value: @movie['release_date']%> </p>
                <p> <%= f.hidden_field :description, :size => 140, value: @movie['overview'] %></p>
                <p> <%= f.hidden_field :image, value: 'https://image.tmdb.org/t/p/w200' + @movie['poster_path'] %></p>
                <h4>サブタイトルを付けるなら？(最大12字)</h4>
                <p> <%= f.text_field :genre, maxlength: "12", :size => 35 %></p>
                <br>
                <h4>感想</h4>
                <p> <%= f.text_area :hoken,:size=>"60x10" %></p>
                <br>
                <br>
                <div class="check_box">
                    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                            <div class='form-check'>
                                <%= tag.label do %>
                                    <%= tag.check_box %>
                                    <%= tag.text %>
                                <% end %>
                            </div>
                    <% end %>
                </div>
                <br>
                <%= f.submit "投稿する" , class: "btn"%>
                <br>
                <br>
        </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="ishimon">
    <br>
    <div class="btn3">
      <%= link_to "映画検索", movies_search_path ,class:'okawa' %>
      <%= link_to "戻る", posts_path ,class:'okawa' %>
    </div>
  <div class="detail1">
    <h1><%= @post.title %></h1>
    <p><%= @post.year %></p>
    <% if @post.image %>
      <%= image_tag @post.image %>
    <% end %>
    <div class="yokohaba">
      <p><%= @post.description %></p>
    </div>  
    <p><%#= @post.created_at %></p>
    <br>
    <p class="review"><%= @post.genre %></p>
    <br>
    <div class="kansou2">
      <%if @post.hoken.nil? %>  
          <%=@post.hoken%>
      <% else %>
        <%=safe_join(@post.hoken.split("\n"),tag(:br))%>    
      <%end %>
    </div>
    <p>================================</p>

    <% @post.tags.each do |tag| %>
        <%= tag.name %>
    <% end %>
    <p>================================</p>
  </div>
  <%#= link_to "編集する", edit_post_path(@post.id) %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>